### ISSUE TITLE
Vertaisarvio 1

### ISSUE THREAD

**Issue by jipeso** [valpyots/tsoha-project-messageboard#1]
Sovelluksen testaaminen sujui hyvin.  Responses valikossa, jos kommentoi kahdella eri käyttäjällä saman kommentin, niin uudemman kommentoijan nimeksi ilmoitetaan aikaisemman kommentoijan nimi eli periaatteessa voi tehdä kommentteja toisen nimellä. Sovellus hyvällä mallilla ja README tiedostossa ilmoitetut toiminnot toimivat hyvin.

**Comment by valpyots** [comment]
Kiitos paljon! Mainitsemasi bugi korjattu.
